name: Deploy to External Repo

on:
  push:
    branches:
      - main # 或者是 main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.MY_DEPLOY_TOKEN }}
          repository-name: fengjinlong/fengjinlong.github.io
          branch: master # 对于 <username>.github.io 仓库，请确保这是你的展示分支
          folder: dist
