name: Deploy Vue3 to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Deploy dist to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 49.232.8.45
          username: root
          password: Web198743@
          source: "dist/"
          target: "/root"
